name: diabetes_manager
description: A complete diabetes management and daily health tracking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  table_calendar: ^3.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
